backend:
  name: git-gateway
  branch: main # or 'master', depending on your repo

media_folder: "public/uploads" # where uploaded files are stored in the repo
public_folder: "/uploads" # path used by the frontend

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "home"
    label: "Home Page Content"
    files:
      - label: "Home Content (English)"
        name: "home_en"
        file: "src/content/home.en.md"
        fields:
          - { label: "Hero Opening", name: "hero_opening", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Button Text", name: "hero_button", widget: "string" }
          - {
              label: "Intro Heading 1",
              name: "intro_heading1",
              widget: "string",
            }
          - {
              label: "Intro Heading 2",
              name: "intro_heading2",
              widget: "string",
            }
          - {
              label: "Intro Subheading",
              name: "intro_subheading",
              widget: "string",
            }
          - {
              label: "Intro Paragraph 1",
              name: "intro_paragraph1",
              widget: "text",
            }
          - {
              label: "Intro Paragraph 2",
              name: "intro_paragraph2",
              widget: "text",
            }
          - { label: "Intro Ending 1", name: "intro_ending1", widget: "string" }
          - { label: "Intro Ending 2", name: "intro_ending2", widget: "string" }

      - label: "Home Content (Japanese)"
        name: "home_ja"
        file: "src/content/home.ja.md"
        fields:
          - {
              label: "ヒーローオープニング",
              name: "hero_opening",
              widget: "string",
            }
          - { label: "ヒーロータイトル", name: "hero_title", widget: "string" }
          - {
              label: "ヒーローボタンテキスト",
              name: "hero_button",
              widget: "string",
            }
          - {
              label: "イントロ見出し1",
              name: "intro_heading1",
              widget: "string",
            }
          - {
              label: "イントロ見出し2",
              name: "intro_heading2",
              widget: "string",
            }
          - {
              label: "イントロサブタイトル",
              name: "intro_subheading",
              widget: "string",
            }
          - { label: "イントロ段落1", name: "intro_paragraph1", widget: "text" }
          - { label: "イントロ段落2", name: "intro_paragraph2", widget: "text" }
          - { label: "締めくくり1", name: "intro_ending1", widget: "string" }
          - { label: "締めくくり2", name: "intro_ending2", widget: "string" }

  - name: "gallery"
    label: "Gallery"
    label_singular: "Image"
    folder: "src/content/Images/gallery"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Alt Text", name: "alt", widget: "string", required: false }

  - name: "contact"
    label: "Contact Info"
    files:
      - label: "Contact Information"
        name: "contact_info"
        file: "src/content/contact.md"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - {
              label: "Google Maps Embed",
              name: "map_iframe",
              widget: "text",
              pattern: [".*iframe.*", "Must be a valid iframe embed"],
            }

  - name: "team"
    label: "Team Members"
    files:
      - label: "Unified Team"
        name: "team_unified"
        file: "src/content/unified_team.md"
        fields:
          - label: "Language"
            name: "lang"
            widget: "hidden"
            default: "unified"
          - label: "Team Members"
            name: "members"
            widget: "list"
            summary: "{{fields.name_en}} / {{fields.name_ja}}"
            fields:
              - { label: "Name (English)", name: "name_en", widget: "string" }
              - { label: "Name (Japanese)", name: "name_ja", widget: "string" }
              - { label: "Role (English)", name: "role_en", widget: "string" }
              - { label: "Role (Japanese)", name: "role_ja", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - {
                  label: "Description (English)",
                  name: "description_en",
                  widget: "text",
                }
              - {
                  label: "Description (Japanese)",
                  name: "description_ja",
                  widget: "text",
                }

  - name: "faq1_services"
    label: "FAQ - Services Section"
    files:
      - label: "FAQ1 (English)"
        name: "faq1_en"
        file: "src/content/faq/faq1/faq1.en.md"
        fields:
          - { label: "Language", name: "lang", widget: "hidden", default: "en" }
          - label: "FAQs"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "FAQ1（日本語）"
        name: "faq1_ja"
        file: "src/content/faq/faq1/faq1.ja.md"
        fields:
          - { label: "言語", name: "lang", widget: "hidden", default: "ja" }
          - label: "よくある質問"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "質問タイトル", name: "title", widget: "string" }
              - { label: "説明", name: "description", widget: "text" }

  - name: "faq2_scholarship"
    label: "FAQ - Scholarship Section"
    files:
      - label: "FAQ2 (English)"
        name: "faq2_en"
        file: "src/content/faq/faq2/faq2.en.md"
        fields:
          - { label: "Language", name: "lang", widget: "hidden", default: "en" }
          - label: "FAQs"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "FAQ2（日本語）"
        name: "faq2_ja"
        file: "src/content/faq/faq2/faq2.ja.md"
        fields:
          - { label: "言語", name: "lang", widget: "hidden", default: "ja" }
          - label: "よくある質問"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "質問タイトル", name: "title", widget: "string" }
              - { label: "説明", name: "description", widget: "text" }

  - name: "faq3_consulting"
    label: "FAQ - Consulting Section"
    files:
      - label: "FAQ3 (English)"
        name: "faq3_en"
        file: "src/content/faq/faq3/faq3.en.md"
        fields:
          - { label: "Language", name: "lang", widget: "hidden", default: "en" }
          - label: "FAQs"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "FAQ3（日本語）"
        name: "faq3_ja"
        file: "src/content/faq/faq3/faq3.ja.md"
        fields:
          - { label: "言語", name: "lang", widget: "hidden", default: "ja" }
          - label: "よくある質問"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "質問タイトル", name: "title", widget: "string" }
              - { label: "説明", name: "description", widget: "text" }

  - name: "faq4_general"
    label: "FAQ - General Section"
    files:
      - label: "FAQ4 (English)"
        name: "faq4_en"
        file: "src/content/faq/faq4/faq4.en.md"
        fields:
          - { label: "Language", name: "lang", widget: "hidden", default: "en" }
          - label: "FAQs"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "FAQ4（日本語）"
        name: "faq4_ja"
        file: "src/content/faq/faq4/faq4.ja.md"
        fields:
          - { label: "言語", name: "lang", widget: "hidden", default: "ja" }
          - label: "よくある質問"
            name: "faqs"
            widget: "list"
            fields:
              - { label: "質問タイトル", name: "title", widget: "string" }
              - { label: "説明", name: "description", widget: "text" }
